# Generated by Django 2.2.5 on 2019-09-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190922_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(default='C:/static/img/dps/default.png', upload_to='C:static/img/dps/'),
        ),
    ]
