# Generated by Django 2.2.5 on 2019-09-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190922_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(default='/static/img/dps/default.png', upload_to='static/img/dps/'),
        ),
    ]
