# Generated by Django 2.2.5 on 2019-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190922_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dp',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/img/dps/default.png', upload_to='static/img/dps/'),
        ),
    ]
