# Generated by Django 2.2.5 on 2019-09-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190922_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='dp',
        ),
    ]
