# Generated by Django 2.2.5 on 2019-09-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190922_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(default='dps/default.png', upload_to='dps/'),
        ),
    ]
